# Site settings
title: Freifunk Ortenau
tagline: das freie WLAN-Netzwerk für die Ortenau 
email: info@ortenau.freifunk.net
description: > # this means to ignore newlines until "baseurl:"
 Freifunk Ortenau ist eine lokale Initiative mit dem Ziel, ein WLAN-Netzwerk über der Ortenau aufzuspannen und freien Internetzugang anzubieten.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ortenau.freifunk.net" # the base hostname & protocol for your site
twitter_username: ffortenau 
github_username:  ffortenau
facebook_username: freifunkortenau
excerpt_separator: <!--*-->

permalink: "news/:year/:month/:day/:title"

# Build settings
markdown: kramdown
exclude: [vendor]
include: [.well-known]
